export const ROUTES = {
  login: '/login',
  item: '/item',
  search: '/search',
  brands: '/brands',
  categories: '/categories',
  affiliates: '/affiliates',
  buy: '/buy',
  legal: '/privacyPolicy',
  admin: {
    brands: '/admin/brands',
    dashboard: '/admin/dashboard',
    login: '/admin/login',
    logout: '/api/auth/logout',
    createCoupon: '/admin/create-coupon',
    coupons: '/admin/coupons',
    createBrand: '/admin/create-brand',
    orders: '/admin/orders',
    orderHistories: '/admin/orders/history',
  },
  recipient_info: '/payments/recipient-info',
};
