export const ROUTES = {
  login: '/login',
  logout: '/api/auth/logout',
  item: '/item',
  search: '/search',
  gpcoupons: '/gpcoupons',
  brands: '/brands',
  categories: '/categories',
  affiliates: '/affiliates',
  howItWorks: '/how-it-works',
  buy: '/buy',
  // privacy: '/privacyPolicy',
  // legal: '/termsOfUse',
  legal: '/legal',
  privacy: '/privacy',
  orders: '/orders',
  confirmAndPay: '/confirm-and-pay',
  occasions: '/occasions',
  paymentCards: '/account/payment-cards',
  affiliateDashboard: '/affiliateDashboard',
  affiliateCouponDetails: '/affiliateDashboard/couponDashboard/details',
  affiliateCouponRequestList: '/affiliateDashboard/coupon/requestList',
  affiliateCouponRequest: '/affiliateDashboard/coupon/request',
  affiliateBrands: '/affiliateDashboard/brands',
  affiliatebrandsList: '/affiliateDashboard/brands/list',
  affiliateCreateBrands: '/affiliateDashboard/brands/create',
  admin: {
    createItem: '/admin/items/create',
    items: '/admin/items',
    brands: '/admin/brands',
    dashboard: '/admin/dashboard',
    // adminDashboard: '/admin/adminDashboard',
    adminDashboardDetails: '/admin/adminDashboardDetails',
    login: '/admin/login',
    logout: '/api/auth/logout',
    createCoupon: '/admin/create-coupon',
    coupons: '/admin/coupons',
    createBrand: '/admin/brands/create',
    listBrands: '/admin/brands',
    orders: '/admin/gpoints/orders',
    createGpoint: '/admin/gpoints/create',
    listGpoints: '/admin/gpoints/list',
    orderHistories: '/admin/orders/history',
  },
  recipient_info: '/payments/recipient-info',
};
